mybatis:
  type-aliases-package: com.liyi.demo.model
server:
  port: 8100
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 123456
    url: jdbc:mysql://47.98.185.103:3306/property_mgt?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8
    username: root
  jackson:
    joda-date-time-format: yyyy-MM-dd
    time-zone: GMT+8
config:
  info: from config-dev.yml,master
